/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import BaseDeDatos.Conexion;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import logica.clases.Cliente;
import logica.clases.Localidad;
import logica.clases.Seccion;
import logica.fabrica.Fabrica;
import logica.interfaces.IEnvio;
import Presentacion.VentanaListarClientes;

/**
 *
 * @author Angelo
 */
public class crearEnvio extends javax.swing.JFrame {

    /**
     * Creates new form crearEnvio
     */
    private Connection connection = new Conexion().getConexion();
    private IEnvio iEnvio; //CREO EL OBJETO INTERFAZ
    private ArrayList<Seccion> listaSecciones = null;
    private ArrayList<Localidad> listaLocalidades = null;
   

    public crearEnvio() {
        initComponents();
        this.iEnvio = Fabrica.getInstancia().getControladorEnvio();
        listaLocalidades = this.iEnvio.listarLocalidades();
        this.cargarListaLocalidades();
        listaSecciones = this.iEnvio.listarSecciones();
        this.cargarListaSecciones();
    }
    //LISTAR OBJETOS DE TIPO SECCION
    private void cargarListaLocalidades() { 
        for (Localidad localidad : listaLocalidades) {
            comboLocalidades.addItem(localidad.getNombre());
        }

    }

    //LISTAR OBJETOS DE TIPO SECCION
    private void cargarListaSecciones() {
        for (Seccion seccion : listaSecciones) {
            comboSecciones.addItem(seccion.getNombre());
        }

    }
    

    //hacer lo mismo que el listar pero con los 9 objetos
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDescPaquete = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        campoPesoPaquete = new javax.swing.JTextField();
        comboFragilPaquete = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboTipoPaquete = new javax.swing.JComboBox<>();
        botonGuardarPaquete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoCalleDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoCalle2Direccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoPuertaDireccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        campoApartDireccion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        comboLocalidades = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        comboSecciones = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        botonListarClientesE = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        campoCedulaE = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        campoNombreE = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        campoApellidoE = new javax.swing.JTextField();
        botonVolverCrearEnvio = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        campoCedulaR = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        campoNombreR = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        campoApellidoR = new javax.swing.JTextField();
        botonListarClientesR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CREAR ENVIO");

        jLabel2.setText("DATOS DEL PAQUETE:");

        jLabel4.setText("Descripción:");

        campoDescPaquete.setColumns(20);
        campoDescPaquete.setRows(5);
        jScrollPane1.setViewportView(campoDescPaquete);

        jLabel5.setText("Peso:");

        campoPesoPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPesoPaqueteActionPerformed(evt);
            }
        });

        comboFragilPaquete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        jLabel6.setText("Fragil:");

        jLabel7.setText("Tipo:");

        comboTipoPaquete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Especial", "Normal" }));
        comboTipoPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoPaqueteActionPerformed(evt);
            }
        });

        botonGuardarPaquete.setText("GUARDAR");
        botonGuardarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarPaqueteActionPerformed(evt);
            }
        });

        jLabel3.setText("DIRECCION DESTINO:");

        jLabel8.setText("Calle:");

        jLabel9.setText("Calle2:");

        campoCalle2Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCalle2DireccionActionPerformed(evt);
            }
        });

        jLabel10.setText("N° Puerta:");

        jLabel11.setText("Apartamento:");

        jLabel12.setText("Localidades:");

        jLabel13.setText("Secciones:");

        comboSecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeccionesActionPerformed(evt);
            }
        });

        jLabel14.setText("CLIENTE EMISOR:");

        botonListarClientesE.setText("Listar Clientes");
        botonListarClientesE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarClientesEActionPerformed(evt);
            }
        });

        jLabel15.setText("Cedula:");

        jLabel16.setText("Nombre:");

        jLabel17.setText("Apellido:");

        botonVolverCrearEnvio.setText("Volver");
        botonVolverCrearEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverCrearEnvioActionPerformed(evt);
            }
        });

        jLabel18.setText("CLIENTE RECEPTOR:");

        jLabel19.setText("Cedula:");

        jLabel20.setText("Nombre:");

        jLabel21.setText("Apellido:");

        botonListarClientesR.setText("Listar Clientes");
        botonListarClientesR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarClientesRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonVolverCrearEnvio)
                        .addGap(360, 360, 360)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoCedulaE, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel2)
                                .addGap(227, 227, 227)
                                .addComponent(jLabel3)
                                .addGap(211, 211, 211)
                                .addComponent(jLabel14)))
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(campoCedulaR, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoNombreR))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoApellidoR))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboTipoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboFragilPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campoPesoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(211, 211, 211)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel11)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(campoPuertaDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                                .addComponent(campoApartDireccion))
                                            .addComponent(comboLocalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(campoCalleDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(campoCalle2Direccion))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonGuardarPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(452, 452, 452))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(comboSecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoApellidoE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(botonListarClientesE, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addComponent(botonListarClientesR, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(campoApellidoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(campoApellidoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(botonVolverCrearEnvio)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(campoCalleDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(campoCedulaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(campoCedulaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(campoCalle2Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(campoNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)
                                    .addComponent(campoNombreR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(campoPesoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(campoPuertaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(campoApartDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonListarClientesE)
                    .addComponent(botonListarClientesR))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboFragilPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(comboLocalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboTipoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(comboSecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(botonGuardarPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoPesoPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPesoPaqueteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPesoPaqueteActionPerformed

    private void comboTipoPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoPaqueteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoPaqueteActionPerformed

    private void botonGuardarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarPaqueteActionPerformed

        // VERFICACION PARA EL PAQUETE
        int fragil = 0, especial = 0, idSeccion = 0;

        if (comboFragilPaquete.getSelectedItem().toString() == "Si") {
            fragil = 1;
        }
        if (comboTipoPaquete.getSelectedItem().toString() == "Especial") {
            especial = 1;
        }
        int idP = this.iEnvio.crearPaquete(campoDescPaquete.getText(), Float.parseFloat(campoPesoPaquete.getText()), fragil, especial);
        campoDescPaquete.setText("");
        campoPesoPaquete.setText(""); //Hacer al final en el boton guardar TODO EL REGISTRO
        //this.ICU.crearDireccion(campoCalleDireccion.getText(), campoCalle2Direccion.getText(), Integer.parseInt(campoPuertaDireccion.getText()), campoApartDireccion.getText());
        //System.out.println("ID autogenerado: " + idP);
        
        //TOMO EL NOMBRE DE LA SECCION QUE QUIERA EL USUARIO
        String nombreSeccion;
        nombreSeccion = comboSecciones.getSelectedItem().toString();
        
        //BUSCA LA SECCION SELECCIONADA EN LA LISTA DE OBJETOS SECCION
        for (Seccion seccion : listaSecciones) {
            if (nombreSeccion.equals(seccion.getNombre())) {
                idSeccion = seccion.getIdSeccion();
                break;
            }
        }
        this.iEnvio.conexionSeccion_Paquete(idP, idSeccion);


    }//GEN-LAST:event_botonGuardarPaqueteActionPerformed

    private void campoCalle2DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCalle2DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCalle2DireccionActionPerformed

    private void comboSeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSeccionesActionPerformed

    private void botonListarClientesEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarClientesEActionPerformed
        // TODO add your handling code here:
        //LLAMAR A VENTANA NUEVA
        VentanaListarClientes VListaClientesE = new VentanaListarClientes();
        VListaClientesE.setVisible(true);
    }//GEN-LAST:event_botonListarClientesEActionPerformed

    private void botonVolverCrearEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverCrearEnvioActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_botonVolverCrearEnvioActionPerformed

    private void botonListarClientesRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarClientesRActionPerformed
        // TODO add your handling code here:
        VentanaListarClientes VListaClientesE = new VentanaListarClientes();
        VListaClientesE.setVisible(true);
    }//GEN-LAST:event_botonListarClientesRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crearEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crearEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crearEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crearEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crearEnvio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarPaquete;
    public static javax.swing.JButton botonListarClientesE;
    private javax.swing.JButton botonListarClientesR;
    private javax.swing.JButton botonVolverCrearEnvio;
    private javax.swing.JTextField campoApartDireccion;
    public static javax.swing.JTextField campoApellidoE;
    private javax.swing.JTextField campoApellidoR;
    private javax.swing.JTextField campoCalle2Direccion;
    private javax.swing.JTextField campoCalleDireccion;
    public static javax.swing.JTextField campoCedulaE;
    private javax.swing.JTextField campoCedulaR;
    private javax.swing.JTextArea campoDescPaquete;
    public static javax.swing.JTextField campoNombreE;
    private javax.swing.JTextField campoNombreR;
    private javax.swing.JTextField campoPesoPaquete;
    private javax.swing.JTextField campoPuertaDireccion;
    private javax.swing.JComboBox<String> comboFragilPaquete;
    private javax.swing.JComboBox<String> comboLocalidades;
    private javax.swing.JComboBox<String> comboSecciones;
    private javax.swing.JComboBox<String> comboTipoPaquete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
