/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logica.fabrica.Fabrica;
import logica.interfaces.IAdministracion;
import Presentacion.CrearEnvio;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author leo
 */
public class CrearCliente extends javax.swing.JFrame {

    private IAdministracion IA;

    /**
     * Creates new form CrearCliente
     */
    public CrearCliente() {
        initComponents();
        this.IA = Fabrica.getInstancia().getControladorCliente();
        this.setLocationRelativeTo(null);
        this.setTitle("Crear Cliente");
        this.setIconImage(new ImageIcon(getClass().getClassLoader().getResource("Images/logo.png")).getImage());
        this.setResizable(false);
    }

    public void llamarAlertaDatosFaltantes() {
        JOptionPane.showMessageDialog(null, "Algún dato de los campos no ha sido ingresado", "Error", JOptionPane.ERROR_MESSAGE);
    }

    public void llamarAlertaClienteCreado() {
        JOptionPane.showMessageDialog(null, "Cliente creado exitosamente", "Creación exitosa", JOptionPane.INFORMATION_MESSAGE);
    }

    public void llamarAlertaClienteExistente() {
        JOptionPane.showMessageDialog(null, "Ya existe un cliente con esa CI en el sistema", "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextFieldNombre = new javax.swing.JTextField();
        TituloCrearUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TituloCrearUsuario1 = new javax.swing.JLabel();
        TextFieldNombre1 = new javax.swing.JTextField();
        TextFieldApellido = new javax.swing.JTextField();
        TextFieldTelefono = new javax.swing.JTextField();
        TextFieldCedula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LabelCorreo = new javax.swing.JLabel();
        TextFieldCorreo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        BotonConfirmar = new javax.swing.JButton();
        volverButton = new javax.swing.JButton();

        TextFieldNombre.setText("Nombre");
        TextFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFieldNombreFocusLost(evt);
            }
        });
        TextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNombreActionPerformed(evt);
            }
        });

        TituloCrearUsuario.setText("Crear usuario");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(406, 329));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo-sm-extra.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 387, 38));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloCrearUsuario1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        TituloCrearUsuario1.setText("CREAR CLIENTE");
        jPanel1.add(TituloCrearUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        TextFieldNombre1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldNombre1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFieldNombre1FocusLost(evt);
            }
        });
        TextFieldNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNombre1ActionPerformed(evt);
            }
        });
        TextFieldNombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldNombre1KeyTyped(evt);
            }
        });
        jPanel1.add(TextFieldNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 130, -1));

        TextFieldApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFieldApellidoFocusLost(evt);
            }
        });
        TextFieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldApellidoActionPerformed(evt);
            }
        });
        TextFieldApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(TextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 130, -1));

        TextFieldTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFieldTelefonoFocusLost(evt);
            }
        });
        TextFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTelefonoActionPerformed(evt);
            }
        });
        TextFieldTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(TextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 130, -1));

        TextFieldCedula.setToolTipText("Ingrese cédula sin punto ni guión");
        TextFieldCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldCedulaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFieldCedulaFocusLost(evt);
            }
        });
        TextFieldCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCedulaActionPerformed(evt);
            }
        });
        TextFieldCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldCedulaKeyTyped(evt);
            }
        });
        jPanel1.add(TextFieldCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 130, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setText("Cédula:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("Apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setText("Teléfono:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        LabelCorreo.setText("Correo:");
        jPanel1.add(LabelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        TextFieldCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(TextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 44, 245, 220));

        BotonConfirmar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        BotonConfirmar.setText("Confirmar");
        BotonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConfirmarActionPerformed(evt);
            }
        });

        volverButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        volverButton.setText("Volver");
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(volverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(BotonConfirmar)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonConfirmar)
                    .addComponent(volverButton))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldCedulaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldCedulaFocusGained

    }//GEN-LAST:event_TextFieldCedulaFocusGained

    private void TextFieldCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldCedulaFocusLost

    }//GEN-LAST:event_TextFieldCedulaFocusLost

    private void TextFieldCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCedulaActionPerformed

    private void TextFieldNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldNombreFocusGained

    }//GEN-LAST:event_TextFieldNombreFocusGained

    private void TextFieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldNombreFocusLost

    }//GEN-LAST:event_TextFieldNombreFocusLost

    private void TextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNombreActionPerformed

    private void TextFieldNombre1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldNombre1FocusGained

    }//GEN-LAST:event_TextFieldNombre1FocusGained

    private void TextFieldNombre1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldNombre1FocusLost

    }//GEN-LAST:event_TextFieldNombre1FocusLost

    private void TextFieldNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNombre1ActionPerformed

    private void TextFieldApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldApellidoFocusGained

    }//GEN-LAST:event_TextFieldApellidoFocusGained

    private void TextFieldApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldApellidoFocusLost

    }//GEN-LAST:event_TextFieldApellidoFocusLost

    private void TextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldApellidoActionPerformed

    private void TextFieldTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldTelefonoFocusGained

    }//GEN-LAST:event_TextFieldTelefonoFocusGained

    private void TextFieldTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldTelefonoFocusLost

    }//GEN-LAST:event_TextFieldTelefonoFocusLost

    private void TextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldTelefonoActionPerformed

    private void BotonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConfirmarActionPerformed
        String verificaCedula = this.TextFieldCedula.getText().trim();
        String nombre = this.TextFieldNombre1.getText().trim();
        String apellido = this.TextFieldApellido.getText().trim();
        String correo = this.TextFieldCorreo.getText().trim();
        String verificaTelefono = this.TextFieldTelefono.getText().trim();
        if (verificaCedula.isBlank() || nombre.isBlank() || apellido.isBlank() || verificaTelefono.isBlank() || correo.isBlank()) {
            llamarAlertaDatosFaltantes();
            return;
        }
        int cedula = Integer.parseInt(this.TextFieldCedula.getText().trim());
        int telefono = Integer.parseInt(this.TextFieldTelefono.getText().trim());
        if (verificaCorreo(correo)) {
            if (this.IA.verificarExisteClienteNuevo(cedula) != true) {
                if (!this.IA.verificarExisteCorreoCliente(correo)) {
                    this.IA.agregarCliente(cedula, nombre, apellido, telefono, correo);
                    llamarAlertaClienteCreado();
                    this.TextFieldCedula.setText("");
                    this.TextFieldApellido.setText("");
                    this.TextFieldNombre.setText("");
                    this.TextFieldNombre1.setText("");
                    this.TextFieldTelefono.setText("");
                    this.TextFieldCorreo.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "El correo ya existe", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                llamarAlertaClienteExistente();
            }
        } else {
            JOptionPane.showMessageDialog(null, "El formato del correo no es correcto", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonConfirmarActionPerformed

    public Boolean verificaCorreo(String correo) {
        // Pauta para la verificación del correo electrónico
        String patronCorreo = "^[A-Za-z0-9+_.-]+@(.+)$";
        Pattern pattern = Pattern.compile(patronCorreo);
        Matcher matcher = pattern.matcher(correo);
        return matcher.matches();
    }


    private void TextFieldCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldCedulaKeyTyped
        int key = evt.getKeyChar();

        if (!Character.isDigit(key)) {
            evt.consume();
        }

        if (TextFieldCedula.getText().trim().length() == 8) {
            evt.consume();
        }
    }//GEN-LAST:event_TextFieldCedulaKeyTyped

    private void TextFieldTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldTelefonoKeyTyped
        int key = evt.getKeyChar();

        if (!Character.isDigit(key)) {
            evt.consume();
        }

        if (TextFieldTelefono.getText().trim().length() == 9) {
            evt.consume();
        }
    }//GEN-LAST:event_TextFieldTelefonoKeyTyped

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed

    }//GEN-LAST:event_jLabel2MousePressed

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_volverButtonActionPerformed

    private void TextFieldNombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldNombre1KeyTyped
        int key = evt.getKeyChar();

        if (TextFieldNombre1.getText().trim().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_TextFieldNombre1KeyTyped

    private void TextFieldApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldApellidoKeyTyped
        int key = evt.getKeyChar();

        if (TextFieldApellido.getText().trim().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_TextFieldApellidoKeyTyped

    private void TextFieldCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonConfirmar;
    private javax.swing.JLabel LabelCorreo;
    private javax.swing.JTextField TextFieldApellido;
    private javax.swing.JTextField TextFieldCedula;
    private javax.swing.JTextField TextFieldCorreo;
    private javax.swing.JTextField TextFieldNombre;
    private javax.swing.JTextField TextFieldNombre1;
    private javax.swing.JTextField TextFieldTelefono;
    private javax.swing.JLabel TituloCrearUsuario;
    private javax.swing.JLabel TituloCrearUsuario1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
