/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import java.util.ArrayList;
import logica.clases.Cliente;
import logica.clases.Localidad;
import logica.clases.Seccion;
import logica.fabrica.Fabrica;
import logica.interfaces.IEnvio;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import logica.clases.Direccion;
import logica.clases.Tarifa;
import logica.interfaces.IAdministracion;

/**
 *
 * @author Angelo
 */
public class CrearEnvio extends javax.swing.JFrame {

    /**
     * Creates new form CrearEnvio
     */
    private final IEnvio iE;
    private final IAdministracion iA;
    private ArrayList<Seccion> listaSecciones = null;
    private ArrayList<Localidad> listaLocalidades = null;
    private ArrayList<Tarifa> listaTarifasEsp = null;
    private int idTarifa = 0;

    public void actualizarTarifasEspeciales() {
        this.limpiarTarifasEspeciales();
        this.cargarListaTarifasEspeciales();
    }

    public CrearEnvio() {
        initComponents();
        labelTipo.setVisible(false);
        checkboxEspecial.setVisible(false);
        this.iE = Fabrica.getInstancia().getControladorEnvio();
        this.iA = Fabrica.getInstancia().getControladorCliente();
        listaLocalidades = this.iE.listarLocalidades();
        this.cargarListaLocalidades();
        listaSecciones = this.iE.listarSecciones();
        this.cargarListaSecciones();
        listaTarifasEsp = this.iE.obtenerTarifasEspeciales();
        this.cargarListaTarifasEspeciales();
        botonCrearTarifaEsp.setVisible(false);
        labelTarifasEspeciales.setVisible(false);
        comboTarifasEspeciales.setVisible(false);
    }

    //LISTAR OBJETOS DE TIPO SECCION
    private void cargarListaLocalidades() {
        listaLocalidades = this.iE.listarLocalidades();
        for (Localidad localidad : this.listaLocalidades) {
            comboLocalidadDestino.addItem(localidad.getNombre());
            comboLocalidadOrigen.addItem(localidad.getNombre());
        }

    }

    //LISTAR OBJETOS DE TIPO SECCION
    private void cargarListaSecciones() {
        listaSecciones = this.iE.listarSecciones();
        for (Seccion seccion : this.listaSecciones) {
            comboSecciones.addItem(seccion.getNombre());
        }

    }

    private void cargarListaTarifasEspeciales() {
        listaTarifasEsp = this.iE.obtenerTarifasEspeciales();
        for (Tarifa tarifa : this.listaTarifasEsp) {
            comboTarifasEspeciales.addItem(tarifa.getNombre());
        }

    }

    private int obtenerIdTarifaEspecial() {
        for (Tarifa tarifaEspecial : this.listaTarifasEsp) {
            if (comboTarifasEspeciales.getSelectedItem().equals(tarifaEspecial.getNombre())) {
                idTarifa = tarifaEspecial.getIdTarifa();
                break;
            }
        }
        return idTarifa;
    }

    private void limpiarTarifasEspeciales() {
        for (Tarifa tarifa : this.listaTarifasEsp) {
            comboTarifasEspeciales.removeItem(tarifa.getNombre());
        }
    }

    private int obtenerIdTarifasNormales(float pesoPaquete) {
        if (pesoPaquete > 0 && pesoPaquete <= 5) {
            return 1;
        } else if (pesoPaquete > 5 && pesoPaquete <= 10) {
            return 2;
        } else if (pesoPaquete > 10 && pesoPaquete <= 15) {
            return 3;
        }
        return 0;
    }

    private void insertarLocalidadDireccion(int idDireccion, String nombreLocalidad) {
        int idLocalidad = 0;

//BUSCA LA LOCALIDAD SELECCIONADA EN LA LISTA DE OBJETOS LOCALIDAD
        for (Localidad localidad : listaLocalidades) {
            if (nombreLocalidad.equals(localidad.getNombre())) {
                idLocalidad = localidad.getIdLocalidad();
                break;
            }
        }

        this.iE.conexionLocalidad_Direccion(idLocalidad, idDireccion);
    }

    private void insertarSeccionPaquete(int idPaquete) {
        int idSeccion = 0;
        String nombreSeccion;
        nombreSeccion = comboSecciones.getSelectedItem().toString();
        for (Seccion seccion : listaSecciones) {
            if (nombreSeccion.equals(seccion.getNombre())) {
                idSeccion = seccion.getIdSeccion();
                break;
            }
        }
        this.iE.conexionSeccion_Paquete(idPaquete, idSeccion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        botonCrearEnvio = new javax.swing.JButton();
        panelPaquete = new javax.swing.JPanel();
        scrollPaneDescrp = new javax.swing.JScrollPane();
        campoDescPaquete = new javax.swing.JTextArea();
        labelDesc = new javax.swing.JLabel();
        campoPesoPaquete = new javax.swing.JTextField();
        labelPeso = new javax.swing.JLabel();
        comboSecciones = new javax.swing.JComboBox<>();
        labelSecciones = new javax.swing.JLabel();
        botonCrearTarifaEsp = new javax.swing.JButton();
        labelTarifasEspeciales = new javax.swing.JLabel();
        comboTarifasEspeciales = new javax.swing.JComboBox<>();
        panelFragil = new javax.swing.JPanel();
        checkBoxFragil = new javax.swing.JCheckBox();
        labelFragil = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        checkboxEspecial = new javax.swing.JCheckBox();
        labelTipo = new javax.swing.JLabel();
        panelDireccionDestino = new javax.swing.JPanel();
        labelCalleD = new javax.swing.JLabel();
        campoCalleDireccion = new javax.swing.JTextField();
        labelCalle2D = new javax.swing.JLabel();
        campoCalle2Direccion = new javax.swing.JTextField();
        campoPuertaDireccion = new javax.swing.JTextField();
        campoApartDireccion = new javax.swing.JTextField();
        labelApartD = new javax.swing.JLabel();
        labelPuertaD = new javax.swing.JLabel();
        comboLocalidadDestino = new javax.swing.JComboBox<>();
        labelLocalidadD = new javax.swing.JLabel();
        panelClienteEmisor = new javax.swing.JPanel();
        campoCedulaE = new javax.swing.JTextField();
        labelCedulaE = new javax.swing.JLabel();
        labelNombree = new javax.swing.JLabel();
        campoNombreE = new javax.swing.JTextField();
        campoApellidoE = new javax.swing.JTextField();
        labelApellidoE = new javax.swing.JLabel();
        labelTelefonoE = new javax.swing.JLabel();
        campoTelefonoE = new javax.swing.JTextField();
        panelClienteReceptor = new javax.swing.JPanel();
        labelCedulaR = new javax.swing.JLabel();
        campoCedulaR = new javax.swing.JTextField();
        labelNombreR = new javax.swing.JLabel();
        campoNombreR = new javax.swing.JTextField();
        labelApellidoR = new javax.swing.JLabel();
        campoApellidoR = new javax.swing.JTextField();
        labelTelefonoR = new javax.swing.JLabel();
        campoTelefonoR = new javax.swing.JTextField();
        panelDireccionOrigen = new javax.swing.JPanel();
        labelCalleO = new javax.swing.JLabel();
        campoCalleDireccionO = new javax.swing.JTextField();
        labelCalle2O = new javax.swing.JLabel();
        campoCalle2DireccionO = new javax.swing.JTextField();
        labelPuertaO = new javax.swing.JLabel();
        campoPuertaDireccionO = new javax.swing.JTextField();
        labelApartO = new javax.swing.JLabel();
        campoApartDireccionO = new javax.swing.JTextField();
        labelLocalidadO = new javax.swing.JLabel();
        comboLocalidadOrigen = new javax.swing.JComboBox<>();
        panelOrigenEnvio = new javax.swing.JPanel();
        checkSucursal = new javax.swing.JCheckBox();
        botonCancelarEnvio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labelTitle.setText("CREAR ENVIO");

        botonCrearEnvio.setText("CREAR ENVIO");
        botonCrearEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearEnvioActionPerformed(evt);
            }
        });

        panelPaquete.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "DATOS DEL PAQUETE:"));

        campoDescPaquete.setColumns(20);
        campoDescPaquete.setRows(5);
        scrollPaneDescrp.setViewportView(campoDescPaquete);

        labelDesc.setText("Descripción:");

        campoPesoPaquete.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoPesoPaqueteFocusLost(evt);
            }
        });
        campoPesoPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPesoPaqueteActionPerformed(evt);
            }
        });
        campoPesoPaquete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoPesoPaqueteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoPesoPaqueteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoPesoPaqueteKeyTyped(evt);
            }
        });

        labelPeso.setText("Peso:");

        comboSecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeccionesActionPerformed(evt);
            }
        });

        labelSecciones.setText("Secciones:");

        botonCrearTarifaEsp.setText("Crear Tarifa Especial");
        botonCrearTarifaEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearTarifaEspActionPerformed(evt);
            }
        });

        labelTarifasEspeciales.setText("Tarifas Especiales:");

        comboTarifasEspeciales.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboTarifasEspecialesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboTarifasEspecialesFocusLost(evt);
            }
        });
        comboTarifasEspeciales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboTarifasEspecialesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comboTarifasEspecialesMousePressed(evt);
            }
        });
        comboTarifasEspeciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTarifasEspecialesActionPerformed(evt);
            }
        });

        checkBoxFragil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxFragilActionPerformed(evt);
            }
        });

        labelFragil.setText("Fragil:");

        javax.swing.GroupLayout panelFragilLayout = new javax.swing.GroupLayout(panelFragil);
        panelFragil.setLayout(panelFragilLayout);
        panelFragilLayout.setHorizontalGroup(
            panelFragilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFragilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFragil)
                .addGap(18, 18, 18)
                .addComponent(checkBoxFragil)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panelFragilLayout.setVerticalGroup(
            panelFragilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFragilLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(panelFragilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFragil)
                    .addComponent(checkBoxFragil))
                .addContainerGap())
        );

        checkboxEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxEspecialActionPerformed(evt);
            }
        });

        labelTipo.setText("Especial: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxEspecial))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkboxEspecial, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPaqueteLayout = new javax.swing.GroupLayout(panelPaquete);
        panelPaquete.setLayout(panelPaqueteLayout);
        panelPaqueteLayout.setHorizontalGroup(
            panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaqueteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPaqueteLayout.createSequentialGroup()
                        .addComponent(panelFragil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPaqueteLayout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPaqueteLayout.createSequentialGroup()
                                .addComponent(labelPeso)
                                .addGap(26, 26, 26)
                                .addComponent(campoPesoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPaqueteLayout.createSequentialGroup()
                                .addComponent(labelDesc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(scrollPaneDescrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))
                    .addGroup(panelPaqueteLayout.createSequentialGroup()
                        .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPaqueteLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(labelTarifasEspeciales)
                                .addGap(18, 18, 18)
                                .addComponent(comboTarifasEspeciales, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPaqueteLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(botonCrearTarifaEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(panelPaqueteLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelSecciones)
                .addGap(18, 18, 18)
                .addComponent(comboSecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelPaqueteLayout.setVerticalGroup(
            panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaqueteLayout.createSequentialGroup()
                .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPaqueteLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(scrollPaneDescrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPaqueteLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(labelDesc)))
                .addGap(18, 18, 18)
                .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPeso)
                    .addComponent(campoPesoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(panelFragil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCrearTarifaEsp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTarifasEspeciales)
                    .addComponent(comboTarifasEspeciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSecciones)
                    .addComponent(comboSecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDireccionDestino.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "DIRECCION DE DESTINO:"));

        labelCalleD.setText("Calle:");

        labelCalle2D.setText("Calle 2:");

        campoCalle2Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCalle2DireccionActionPerformed(evt);
            }
        });

        campoPuertaDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoPuertaDireccionKeyTyped(evt);
            }
        });

        labelApartD.setText("Apartamento:");

        labelPuertaD.setText("N° Puerta:");

        comboLocalidadDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLocalidadDestinoActionPerformed(evt);
            }
        });

        labelLocalidadD.setText("Localidad:");

        javax.swing.GroupLayout panelDireccionDestinoLayout = new javax.swing.GroupLayout(panelDireccionDestino);
        panelDireccionDestino.setLayout(panelDireccionDestinoLayout);
        panelDireccionDestinoLayout.setHorizontalGroup(
            panelDireccionDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDireccionDestinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDireccionDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDireccionDestinoLayout.createSequentialGroup()
                        .addGroup(panelDireccionDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelDireccionDestinoLayout.createSequentialGroup()
                                .addComponent(labelCalleD)
                                .addGap(18, 18, 18)
                                .addComponent(campoCalleDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDireccionDestinoLayout.createSequentialGroup()
                                .addComponent(labelCalle2D)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoCalle2Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88)
                        .addGroup(panelDireccionDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelApartD)
                            .addComponent(labelPuertaD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDireccionDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoPuertaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoApartDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDireccionDestinoLayout.createSequentialGroup()
                        .addComponent(labelLocalidadD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboLocalidadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDireccionDestinoLayout.setVerticalGroup(
            panelDireccionDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDireccionDestinoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelDireccionDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCalleD)
                    .addComponent(campoCalleDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPuertaD)
                    .addComponent(campoPuertaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelDireccionDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDireccionDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelApartD)
                        .addComponent(campoApartDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDireccionDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCalle2D)
                        .addComponent(campoCalle2Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelDireccionDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLocalidadD)
                    .addComponent(comboLocalidadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        panelClienteEmisor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "CLIENTE EMISOR:"));

        campoCedulaE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCedulaEFocusLost(evt);
            }
        });
        campoCedulaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCedulaEActionPerformed(evt);
            }
        });
        campoCedulaE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCedulaEKeyTyped(evt);
            }
        });

        labelCedulaE.setText("Cedula:");

        labelNombree.setText("Nombre:");

        labelApellidoE.setText("Apellido:");

        labelTelefonoE.setText("Teléfono:");

        campoTelefonoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelefonoEActionPerformed(evt);
            }
        });
        campoTelefonoE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoTelefonoEKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelClienteEmisorLayout = new javax.swing.GroupLayout(panelClienteEmisor);
        panelClienteEmisor.setLayout(panelClienteEmisorLayout);
        panelClienteEmisorLayout.setHorizontalGroup(
            panelClienteEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteEmisorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelClienteEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelClienteEmisorLayout.createSequentialGroup()
                        .addComponent(labelApellidoE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoApellidoE))
                    .addGroup(panelClienteEmisorLayout.createSequentialGroup()
                        .addComponent(labelNombree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNombreE))
                    .addGroup(panelClienteEmisorLayout.createSequentialGroup()
                        .addComponent(labelTelefonoE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTelefonoE, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClienteEmisorLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelCedulaE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCedulaE, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelClienteEmisorLayout.setVerticalGroup(
            panelClienteEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteEmisorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelClienteEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCedulaE)
                    .addComponent(campoCedulaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelClienteEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombree)
                    .addComponent(campoNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelClienteEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellidoE)
                    .addComponent(campoApellidoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelClienteEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefonoE)
                    .addComponent(campoTelefonoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panelClienteReceptor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "CLIENTE RECEPTOR:"));

        labelCedulaR.setText("Cedula:");

        campoCedulaR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCedulaRFocusLost(evt);
            }
        });
        campoCedulaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCedulaRActionPerformed(evt);
            }
        });
        campoCedulaR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCedulaRKeyTyped(evt);
            }
        });

        labelNombreR.setText("Nombre:");

        campoNombreR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreRActionPerformed(evt);
            }
        });

        labelApellidoR.setText("Apellido:");

        labelTelefonoR.setText("Teléfono:");

        campoTelefonoR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoTelefonoRKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelClienteReceptorLayout = new javax.swing.GroupLayout(panelClienteReceptor);
        panelClienteReceptor.setLayout(panelClienteReceptorLayout);
        panelClienteReceptorLayout.setHorizontalGroup(
            panelClienteReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteReceptorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelClienteReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelClienteReceptorLayout.createSequentialGroup()
                        .addComponent(labelCedulaR)
                        .addGap(18, 18, 18)
                        .addComponent(campoCedulaR, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClienteReceptorLayout.createSequentialGroup()
                        .addGroup(panelClienteReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelApellidoR)
                            .addComponent(labelNombreR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelClienteReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoApellidoR, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNombreR, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelClienteReceptorLayout.createSequentialGroup()
                        .addComponent(labelTelefonoR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoTelefonoR)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelClienteReceptorLayout.setVerticalGroup(
            panelClienteReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteReceptorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelClienteReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCedulaR)
                    .addComponent(campoCedulaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelClienteReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClienteReceptorLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panelClienteReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombreR)
                            .addComponent(campoNombreR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelClienteReceptorLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(panelClienteReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoApellidoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelApellidoR))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelClienteReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTelefonoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTelefonoR))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDireccionOrigen.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "DIRECCION DE ORIGEN:"));

        labelCalleO.setText("Calle:");

        campoCalleDireccionO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCalleDireccionOFocusGained(evt);
            }
        });
        campoCalleDireccionO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCalleDireccionOActionPerformed(evt);
            }
        });

        labelCalle2O.setText("Calle 2:");

        campoCalle2DireccionO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCalle2DireccionOActionPerformed(evt);
            }
        });

        labelPuertaO.setText("N° Puerta:");

        campoPuertaDireccionO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPuertaDireccionOActionPerformed(evt);
            }
        });
        campoPuertaDireccionO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoPuertaDireccionOKeyTyped(evt);
            }
        });

        labelApartO.setText("Apartamento:");

        labelLocalidadO.setText("Localidad:");

        javax.swing.GroupLayout panelDireccionOrigenLayout = new javax.swing.GroupLayout(panelDireccionOrigen);
        panelDireccionOrigen.setLayout(panelDireccionOrigenLayout);
        panelDireccionOrigenLayout.setHorizontalGroup(
            panelDireccionOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDireccionOrigenLayout.createSequentialGroup()
                .addGroup(panelDireccionOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDireccionOrigenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDireccionOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelDireccionOrigenLayout.createSequentialGroup()
                                .addComponent(labelCalleO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoCalleDireccionO, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDireccionOrigenLayout.createSequentialGroup()
                                .addComponent(labelCalle2O)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoCalle2DireccionO)))
                        .addGap(42, 42, 42)
                        .addGroup(panelDireccionOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPuertaO)
                            .addComponent(labelApartO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDireccionOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoPuertaDireccionO)
                            .addComponent(campoApartDireccionO, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDireccionOrigenLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(labelLocalidadO, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboLocalidadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDireccionOrigenLayout.setVerticalGroup(
            panelDireccionOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDireccionOrigenLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelDireccionOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDireccionOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelDireccionOrigenLayout.createSequentialGroup()
                            .addComponent(labelPuertaO)
                            .addGap(31, 31, 31)
                            .addComponent(labelApartO))
                        .addGroup(panelDireccionOrigenLayout.createSequentialGroup()
                            .addGroup(panelDireccionOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelCalleO)
                                .addComponent(campoCalleDireccionO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(23, 23, 23)
                            .addGroup(panelDireccionOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelCalle2O)
                                .addComponent(campoCalle2DireccionO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelDireccionOrigenLayout.createSequentialGroup()
                        .addComponent(campoPuertaDireccionO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campoApartDireccionO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(panelDireccionOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLocalidadO)
                    .addComponent(comboLocalidadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        panelOrigenEnvio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "ORIGEN DE ENVIO:"));

        checkSucursal.setText("Sucursal");
        checkSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSucursalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOrigenEnvioLayout = new javax.swing.GroupLayout(panelOrigenEnvio);
        panelOrigenEnvio.setLayout(panelOrigenEnvioLayout);
        panelOrigenEnvioLayout.setHorizontalGroup(
            panelOrigenEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrigenEnvioLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(checkSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panelOrigenEnvioLayout.setVerticalGroup(
            panelOrigenEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrigenEnvioLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(checkSucursal)
                .addGap(15, 15, 15))
        );

        botonCancelarEnvio.setText("CANCELAR");
        botonCancelarEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarEnvioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelClienteEmisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(panelClienteReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(panelDireccionDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panelDireccionOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(panelOrigenEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(botonCancelarEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonCrearEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(panelPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelClienteReceptor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelClienteEmisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelDireccionDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelOrigenEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(panelDireccionOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonCancelarEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCrearEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoPesoPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPesoPaqueteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPesoPaqueteActionPerformed

    private void botonCrearEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearEnvioActionPerformed
        if (this.validacionCamposVacios() && this.validacionDeClientes()) {

            int idSeccion = 0, idLocalidadDestino = 0, idLocalidadOrigen = 0,
                    idDireccionOrigen = 0, idDireccionDestino = 0;
            boolean tipoEntrega;
            int fragil = this.checkBoxFragil.isSelected() ? 1 : 0;
            int especial = this.checkboxEspecial.isSelected() ? 1 : 0;
            if(especial==1){
                idTarifa = this.obtenerIdTarifaEspecial();
            }
            int idP = this.iE.crearPaquete(campoDescPaquete.getText(), Float.parseFloat(campoPesoPaquete.getText()), fragil, especial);
            if (this.validacionCamposVacios()) {
                idDireccionDestino = this.iE.crearDireccion(campoCalleDireccion.getText(), campoCalle2Direccion.getText(),
                        Integer.parseInt(campoPuertaDireccion.getText()), campoApartDireccion.getText());
            }
            //IDLOCALIDADDESTINO
//----------CREACION DE LA DIRECCION SUCURSAL-----------------------------------------------------------------------------------------------

            if (checkSucursal.isSelected()) {
                Direccion sucursal = this.iE.traerDireccionSucursal();
                idDireccionOrigen = sucursal.getIdDireccion();
            } else {
//------CREACION DE LA DIRECCION ORIGEN-----------------------------------------------------------------------------------------------------
                idDireccionOrigen = this.iE.crearDireccion(campoCalleDireccionO.getText(), campoCalle2DireccionO.getText(),
                        Integer.parseInt(campoPuertaDireccionO.getText()), campoApartDireccionO.getText());
                this.insertarLocalidadDireccion(idDireccionOrigen, comboLocalidadOrigen.getSelectedItem().toString());
            }
//----------------SECCION-PAQUETE------------------------------------------------------------------------------------------
            this.insertarSeccionPaquete(idP);
//-----------------------------------------------------------------------------------------------------------------------------
            this.insertarLocalidadDireccion(idDireccionDestino, comboLocalidadDestino.getSelectedItem().toString());
//----------------------------------------------------------------------------------------------------------------------------
            //ENVIO

            int idEnvio = this.iE.crearEnvio(idP, idTarifa, idDireccionOrigen, idDireccionDestino, -1);

//----------CLIENTES-----------------------------------------------------------------------------------------------------------------------------------------------------------------
            if (!this.iA.verificarExisteClienteNuevo(Integer.parseInt(campoCedulaE.getText()))) {
                this.iA.agregarCliente(Integer.parseInt(campoCedulaE.getText()), campoNombreE.getText(),
                        campoApellidoE.getText(), Integer.parseInt(campoTelefonoE.getText()));
            }
            if (!this.iA.verificarExisteClienteNuevo(Integer.parseInt(campoCedulaR.getText()))) {
                this.iA.agregarCliente(Integer.parseInt(campoCedulaR.getText()),
                        campoNombreR.getText(), campoApellidoR.getText(),
                        Integer.parseInt(campoTelefonoR.getText().trim()));
            }
//-----CONEXION ENVIO Y CLIENTE------------------------------------------------------------------------------------
            this.iE.conexionEnvio_Cliente(idEnvio, Integer.parseInt(campoCedulaE.getText()), "Envio");
            this.iE.conexionEnvio_Cliente(idEnvio, Integer.parseInt(campoCedulaR.getText()), "Recibe");
//---CONEXION ENVIO Y ESTADO-------------------------------------------------------------------------------------
            this.iE.crearEstado(idEnvio, "Preparando", "Creacion del envio");

            JOptionPane.showMessageDialog(null, "El envio fue ingresado con éxito", "Success", JOptionPane.DEFAULT_OPTION);
            this.setVisible(false);
            Home home = new Home();
            home.setVisible(true);
        } else if (!this.validacionTarifas()){
            JOptionPane.showMessageDialog(null, "Falta seleccionar la tarifa", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!this.validacionSecciones()){
            JOptionPane.showMessageDialog(null, "Falta seleccionar la seccion", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!this.validacionCamposVacios()) {
            JOptionPane.showMessageDialog(null, "Para registrar el envio tiene que completar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Los clientes tienen que ser diferentes", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonCrearEnvioActionPerformed

    private void campoCalle2DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCalle2DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCalle2DireccionActionPerformed

    private void comboSeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSeccionesActionPerformed

    private void campoCedulaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCedulaEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCedulaEActionPerformed

    private void campoCedulaEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCedulaEFocusLost
        this.completarDatosCliente(this.campoCedulaE, this.campoNombreE, this.campoApellidoE, this.campoTelefonoE);
    }//GEN-LAST:event_campoCedulaEFocusLost

    private void campoCedulaRFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCedulaRFocusLost
        this.completarDatosCliente(this.campoCedulaR, this.campoNombreR, this.campoApellidoR, this.campoTelefonoR);
    }//GEN-LAST:event_campoCedulaRFocusLost

    private void completarDatosCliente(JTextField campoCedula, JTextField campoNombre, JTextField campoApellido, JTextField campoTelefono) {
        Cliente cliente = !campoCedula.getText().isBlank()
                ? this.iE.traerCliente(Integer.parseInt(campoCedula.getText())) : null;
        if (cliente != null) {
            campoCedula.setText(String.valueOf(cliente.getCedula()));
            campoNombre.setText(cliente.getNombre());
            campoApellido.setText(cliente.getApellido());
            campoTelefono.setText(cliente.getTelefono());
        } else {
            campoNombre.setText("");
            campoApellido.setText("");
            campoTelefono.setText("");
        }
    }

    private void checkSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSucursalActionPerformed
        // TODO add your handling code here:
        if (checkSucursal.isSelected()) {
            campoCalleDireccionO.setEnabled(false);
            campoCalleDireccionO.setText(" ");
            campoCalle2DireccionO.setEnabled(false);
            campoCalle2DireccionO.setText(" ");
            campoPuertaDireccionO.setEnabled(false);
            campoPuertaDireccionO.setText(" ");
            campoApartDireccionO.setEnabled(false);
            campoApartDireccionO.setText(" ");
            comboLocalidadOrigen.setEnabled(false);
        } else {
            campoCalleDireccionO.setEnabled(true);
            campoCalle2DireccionO.setEnabled(true);
            campoPuertaDireccionO.setEnabled(true);
            campoApartDireccionO.setEnabled(true);

        }
    }//GEN-LAST:event_checkSucursalActionPerformed

    private void campoCalleDireccionOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCalleDireccionOActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_campoCalleDireccionOActionPerformed

    private void campoCalleDireccionOFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCalleDireccionOFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_campoCalleDireccionOFocusGained

    private void campoCalle2DireccionOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCalle2DireccionOActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_campoCalle2DireccionOActionPerformed

    private void campoPesoPaqueteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPesoPaqueteKeyTyped
        // TODO add your handling code here:
        //METODO PARA NO ACEPTAR LA ENTRADA DE LETRAS
        int key = evt.getKeyChar();

        if (!Character.isDigit(key) && key != '.' || key == '.' && campoPesoPaquete.getText().contains(".") || campoPesoPaquete.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_campoPesoPaqueteKeyTyped

    private void campoPuertaDireccionOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPuertaDireccionOActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_campoPuertaDireccionOActionPerformed

    private void campoPuertaDireccionOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPuertaDireccionOKeyTyped
        // TODO add your handling code here:
        //METODO PARA NO ACEPTAR LA ENTRADA DE LETRAS
        int key = evt.getKeyChar();

        if (!Character.isDigit(key) || campoPuertaDireccionO.getText().length() >= 11) {
            evt.consume();
        }
    }//GEN-LAST:event_campoPuertaDireccionOKeyTyped

    private void campoPuertaDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPuertaDireccionKeyTyped
        // TODO add your handling code here:
        //METODO PARA NO ACEPTAR LA ENTRADA DE LETRAS
        int key = evt.getKeyChar();

        if (!Character.isDigit(key) || campoPuertaDireccion.getText().length() >= 11) {
            evt.consume();
        }
    }//GEN-LAST:event_campoPuertaDireccionKeyTyped

    private void campoCedulaEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCedulaEKeyTyped
        int key = evt.getKeyChar();

        if (!Character.isDigit(key) || campoCedulaE.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_campoCedulaEKeyTyped

    private void campoCedulaRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCedulaRKeyTyped
        // TODO add your handling code here:
        //METODO PARA NO ACEPTAR LA ENTRADA DE LETRAS
        int key = evt.getKeyChar();

        if (!Character.isDigit(key) || campoCedulaR.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_campoCedulaRKeyTyped

    private void campoTelefonoEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTelefonoEKeyTyped
        // TODO add your handling code here:
        //METODO PARA NO ACEPTAR LA ENTRADA DE LETRAS
        int key = evt.getKeyChar();

        if (!Character.isDigit(key) || campoTelefonoE.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_campoTelefonoEKeyTyped

    private void campoTelefonoRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTelefonoRKeyTyped
        // TODO add your handling code here:
        //METODO PARA NO ACEPTAR LA ENTRADA DE LETRAS
        int key = evt.getKeyChar();

        if (!Character.isDigit(key) || campoTelefonoR.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_campoTelefonoRKeyTyped

    private boolean validacionCamposVacios() {
        return this.validacionCamposDireccionD() && this.validacionCamposDireccionO()
                && this.validacionCamposClienteE() && this.validacionCamposClienteR() && !this.campoPesoPaquete.getText().isBlank() 
                && this.validacionTarifas()&& this.validacionSecciones();
    }

    private boolean validacionCamposDireccionD() {
        return !this.campoCalleDireccion.getText().isBlank() && !this.campoPuertaDireccion.getText().isBlank();
    }

    private boolean validacionCamposDireccionO() {
        return this.checkSucursal.isSelected() || (!this.campoCalleDireccion.getText().isBlank()
                && !this.campoPuertaDireccion.getText().isBlank());
    }

    private boolean validacionCamposClienteR() {
        return !this.campoCedulaR.getText().isBlank() && !this.campoNombreR.getText().isBlank()
                && !this.campoApellidoR.getText().isBlank() && !this.campoTelefonoR.getText().isBlank();
    }

    private boolean validacionCamposClienteE() {
        return !this.campoCedulaE.getText().isBlank() && !this.campoNombreE.getText().isBlank()
                && !this.campoApellidoE.getText().isBlank() && !this.campoTelefonoE.getText().isBlank();
    }

    private boolean validacionDeClientes() {
        return !(this.campoCedulaE.getText().equals(this.campoCedulaR.getText()));
    }
    
    private boolean validacionTarifas() {
        return this.comboTarifasEspeciales.getSelectedItem() != null;
    }
    
    private boolean validacionSecciones() {
        return this.comboSecciones.getSelectedItem() != null;
    }

    private void botonCrearTarifaEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearTarifaEspActionPerformed
        // TODO add your handling code here:
        CrearTarifa Vcreartarifa = new CrearTarifa(this);
        Vcreartarifa.setVisible(true);
    }//GEN-LAST:event_botonCrearTarifaEspActionPerformed

    private void comboTarifasEspecialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTarifasEspecialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTarifasEspecialesActionPerformed

    private void comboTarifasEspecialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboTarifasEspecialesMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_comboTarifasEspecialesMouseClicked

    private void comboTarifasEspecialesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboTarifasEspecialesFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_comboTarifasEspecialesFocusGained

    private void comboTarifasEspecialesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboTarifasEspecialesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTarifasEspecialesMousePressed

    private void checkboxEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxEspecialActionPerformed

    }//GEN-LAST:event_checkboxEspecialActionPerformed

    private void campoPesoPaqueteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPesoPaqueteFocusLost
        if (!campoPesoPaquete.getText().isBlank()) {
            float peso = Float.parseFloat(campoPesoPaquete.getText());
            if (checkboxEspecial.isSelected() && peso > 15) {
                this.labelTipo.setVisible(true);
                this.checkboxEspecial.setVisible(true);
                this.checkboxEspecial.setSelected(true);
                this.checkboxEspecial.setEnabled(false);
                this.botonCrearTarifaEsp.setVisible(true);
                this.comboTarifasEspeciales.setVisible(true);
                this.labelTarifasEspeciales.setVisible(true);
            } else {
                this.labelTipo.setVisible(false);
                this.checkboxEspecial.setVisible(false);
                this.checkboxEspecial.doClick();
                this.botonCrearTarifaEsp.setVisible(false);
                this.labelTarifasEspeciales.setVisible(false);
                this.comboTarifasEspeciales.setVisible(false);
                this.idTarifa = this.obtenerIdTarifasNormales(peso);
            }
        }
    }//GEN-LAST:event_campoPesoPaqueteFocusLost

    private void comboLocalidadDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLocalidadDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboLocalidadDestinoActionPerformed

    private void campoCedulaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCedulaRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCedulaRActionPerformed

    private void comboTarifasEspecialesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboTarifasEspecialesFocusLost
       
    }//GEN-LAST:event_comboTarifasEspecialesFocusLost

    private void campoNombreRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreRActionPerformed

    private void campoTelefonoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefonoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefonoEActionPerformed

    private void botonCancelarEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarEnvioActionPerformed
        Home home = new Home();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonCancelarEnvioActionPerformed

    private void checkBoxFragilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxFragilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxFragilActionPerformed

    private void campoPesoPaqueteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPesoPaqueteKeyPressed

        if (!campoPesoPaquete.getText().isBlank()) {
            float peso = Float.parseFloat(campoPesoPaquete.getText());
            if (checkboxEspecial.isSelected() && peso > 15) {
                labelTipo.setVisible(true);
                checkboxEspecial.setVisible(true);
                checkboxEspecial.setSelected(true);
                this.checkboxEspecial.setEnabled(false);
            } else {
                labelTipo.setVisible(false);
                checkboxEspecial.setVisible(false);
                checkboxEspecial.doClick();
                botonCrearTarifaEsp.setVisible(false);
                labelTarifasEspeciales.setVisible(false);
                comboTarifasEspeciales.setVisible(false);
                idTarifa = this.obtenerIdTarifasNormales(peso);
            }
        }
    }//GEN-LAST:event_campoPesoPaqueteKeyPressed

    private void campoPesoPaqueteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPesoPaqueteKeyReleased
        if (!campoPesoPaquete.getText().isBlank()) {
            float peso = Float.parseFloat(campoPesoPaquete.getText());
            if (checkboxEspecial.isSelected() && peso > 15) {
                this.labelTipo.setVisible(true);
                this.checkboxEspecial.setVisible(true);
                this.checkboxEspecial.setSelected(true);
                this.checkboxEspecial.setEnabled(false);
                this.botonCrearTarifaEsp.setVisible(true);
                this.comboTarifasEspeciales.setVisible(true);
                this.labelTarifasEspeciales.setVisible(true);
            } else {
                this.labelTipo.setVisible(false);
                this.checkboxEspecial.setVisible(false);
                this.checkboxEspecial.doClick();
                this.botonCrearTarifaEsp.setVisible(false);
                this.labelTarifasEspeciales.setVisible(false);
                this.comboTarifasEspeciales.setVisible(false);
                this.idTarifa = this.obtenerIdTarifasNormales(peso);
            }
        }
    }//GEN-LAST:event_campoPesoPaqueteKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearEnvio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearEnvio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearEnvio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearEnvio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearEnvio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelarEnvio;
    private javax.swing.JButton botonCrearEnvio;
    private javax.swing.JButton botonCrearTarifaEsp;
    private javax.swing.JTextField campoApartDireccion;
    private javax.swing.JTextField campoApartDireccionO;
    private javax.swing.JTextField campoApellidoE;
    private javax.swing.JTextField campoApellidoR;
    private javax.swing.JTextField campoCalle2Direccion;
    private javax.swing.JTextField campoCalle2DireccionO;
    private javax.swing.JTextField campoCalleDireccion;
    private javax.swing.JTextField campoCalleDireccionO;
    private javax.swing.JTextField campoCedulaE;
    private javax.swing.JTextField campoCedulaR;
    private javax.swing.JTextArea campoDescPaquete;
    private javax.swing.JTextField campoNombreE;
    private javax.swing.JTextField campoNombreR;
    private javax.swing.JTextField campoPesoPaquete;
    private javax.swing.JTextField campoPuertaDireccion;
    private javax.swing.JTextField campoPuertaDireccionO;
    private javax.swing.JTextField campoTelefonoE;
    private javax.swing.JTextField campoTelefonoR;
    private javax.swing.JCheckBox checkBoxFragil;
    private javax.swing.JCheckBox checkSucursal;
    private javax.swing.JCheckBox checkboxEspecial;
    private javax.swing.JComboBox<String> comboLocalidadDestino;
    private javax.swing.JComboBox<String> comboLocalidadOrigen;
    private javax.swing.JComboBox<String> comboSecciones;
    private javax.swing.JComboBox<String> comboTarifasEspeciales;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelApartD;
    private javax.swing.JLabel labelApartO;
    private javax.swing.JLabel labelApellidoE;
    private javax.swing.JLabel labelApellidoR;
    private javax.swing.JLabel labelCalle2D;
    private javax.swing.JLabel labelCalle2O;
    private javax.swing.JLabel labelCalleD;
    private javax.swing.JLabel labelCalleO;
    private javax.swing.JLabel labelCedulaE;
    private javax.swing.JLabel labelCedulaR;
    private javax.swing.JLabel labelDesc;
    private javax.swing.JLabel labelFragil;
    private javax.swing.JLabel labelLocalidadD;
    private javax.swing.JLabel labelLocalidadO;
    private javax.swing.JLabel labelNombreR;
    private javax.swing.JLabel labelNombree;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JLabel labelPuertaD;
    private javax.swing.JLabel labelPuertaO;
    private javax.swing.JLabel labelSecciones;
    private javax.swing.JLabel labelTarifasEspeciales;
    private javax.swing.JLabel labelTelefonoE;
    private javax.swing.JLabel labelTelefonoR;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelClienteEmisor;
    private javax.swing.JPanel panelClienteReceptor;
    private javax.swing.JPanel panelDireccionDestino;
    private javax.swing.JPanel panelDireccionOrigen;
    private javax.swing.JPanel panelFragil;
    private javax.swing.JPanel panelOrigenEnvio;
    private javax.swing.JPanel panelPaquete;
    private javax.swing.JScrollPane scrollPaneDescrp;
    // End of variables declaration//GEN-END:variables
}
