/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.clases.Localidad;
import logica.clases.Seccion;
import logica.clases_customs.TableActionCellEditor;
import logica.clases_customs.TableActionCellRender;
import logica.fabrica.Fabrica;
import logica.interfaces.ITableActionEvent;

/**
 *
 * @author franc
 */
public class ListarSecciones extends javax.swing.JFrame {

    private Fabrica fb;

    /**
     * Creates new form ListarSecciones
     */
    public ListarSecciones() {
        initComponents();
        this.setResizable(false);
        this.fb = Fabrica.getInstancia();
        this.cargarListaSecciones();
        ITableActionEvent event = new ITableActionEvent() {

            @Override
            public void onEdit(int id) {
                EditarSeccion editSeccion = new EditarSeccion(id);
                editSeccion.setVisible(true);
                dispose();
            }

            @Override
            public void onDelete(int id, int row) {
                if (fb.getControladorSeccion().eliminarSeccion(id)) {
                    JOptionPane.showMessageDialog(null, "La sección fue eliminada con exito", "Success", JOptionPane.DEFAULT_OPTION);
                    if (tablaSecciones.isEditing()) {
                        tablaSecciones.getCellEditor().stopCellEditing();
                    }
                    DefaultTableModel model = (DefaultTableModel) tablaSecciones.getModel();
                    model.removeRow(row);
                } else {
                    JOptionPane.showMessageDialog(null, "La sección esta en uso por lo que no se puede eliminar", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

            @Override
            public void onView(int id) {
                //
            }
        };
        this.tablaSecciones.getColumnModel().getColumn(4).setCellRenderer(new TableActionCellRender());
        this.tablaSecciones.getColumnModel().getColumn(4).setCellEditor(new TableActionCellEditor(event));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        crearSeccionButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSecciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("SECCIONES");

        crearSeccionButton.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        crearSeccionButton.setText("Crear sección");
        crearSeccionButton.setPreferredSize(new java.awt.Dimension(93, 23));
        crearSeccionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearSeccionButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tablaSecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Cantidad", "Localidad", "Acciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaSecciones.setRowHeight(30);
        jScrollPane1.setViewportView(tablaSecciones);
        if (tablaSecciones.getColumnModel().getColumnCount() > 0) {
            tablaSecciones.getColumnModel().getColumn(0).setMinWidth(0);
            tablaSecciones.getColumnModel().getColumn(0).setPreferredWidth(0);
            tablaSecciones.getColumnModel().getColumn(0).setMaxWidth(0);
            tablaSecciones.getColumnModel().getColumn(1).setResizable(false);
            tablaSecciones.getColumnModel().getColumn(1).setPreferredWidth(75);
            tablaSecciones.getColumnModel().getColumn(2).setResizable(false);
            tablaSecciones.getColumnModel().getColumn(2).setPreferredWidth(16);
            tablaSecciones.getColumnModel().getColumn(3).setResizable(false);
            tablaSecciones.getColumnModel().getColumn(3).setPreferredWidth(86);
            tablaSecciones.getColumnModel().getColumn(4).setResizable(false);
            tablaSecciones.getColumnModel().getColumn(4).setPreferredWidth(12);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(crearSeccionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(crearSeccionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearSeccionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearSeccionButtonActionPerformed
        // TODO add your handling code here:
        CrearSeccion crearSeccion = new CrearSeccion();
        crearSeccion.setVisible(true);
        dispose();
    }//GEN-LAST:event_crearSeccionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarSecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarSecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarSecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarSecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarSecciones().setVisible(true);
            }
        });
    }

    private void cargarListaSecciones() {
        ArrayList<Seccion> listaDeSecciones = this.fb.getControladorSeccion().obtenerSecciones();
        ArrayList<Localidad> listaDeLocalidades = this.fb.getControladorLocalidad().obtenerLocalidades();
        String localidad = "";
        DefaultTableModel modelo = (DefaultTableModel) this.tablaSecciones.getModel();
        for (Seccion sec : listaDeSecciones) {
            for (Localidad loc : listaDeLocalidades) {
                if (sec.getIdLocalidad() == loc.getIdLocalidad()) {
                    localidad = loc.getZona();
                }
            }
            Object[] row = {sec.getIdSeccion(), sec.getNombre(), sec.getCantidad(), localidad};
            modelo.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearSeccionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSecciones;
    // End of variables declaration//GEN-END:variables
}
