/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.clases.Localidad;
import logica.clases.Seccion;
import logica.clases_customs.CenterRenderer;
import logica.clases_customs.TableActionCellEditor;
import logica.clases_customs.TableActionCellRender;
import logica.fabrica.Fabrica;
import logica.interfaces.ITableActionEvent;

/**
 *
 * @author franc
 */
public class ListarSecciones extends javax.swing.JFrame {

    private Fabrica fb;
    private ListarSecciones listarSecciones = null;
    private ITableActionEvent event = null;
    /**
     * Creates new form ListarSecciones
     */
    public ListarSecciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("MLEntregas");
        this.setIconImage(new ImageIcon(getClass().getClassLoader().getResource("Images/logo.png")).getImage());
        this.setResizable(false);
        this.listarSecciones = this;
        this.fb = Fabrica.getInstancia();
        this.cargarListaSecciones();
        event = new ITableActionEvent() {

            @Override
            public void onEdit(int id) {
                EditarSeccion editSeccion = new EditarSeccion(id, listarSecciones);
                editSeccion.setVisible(true);
            }

            @Override
            public void onDelete(int id, int row) {
                if (fb.getControladorSeccion().eliminarSeccion(id)) {
                    JOptionPane.showMessageDialog(null, "La sección fue eliminada con exito", "Success", JOptionPane.DEFAULT_OPTION);
                    if (tablaSecciones.isEditing()) {
                        tablaSecciones.getCellEditor().stopCellEditing();
                    }
                    DefaultTableModel model = (DefaultTableModel) tablaSecciones.getModel();
                    model.removeRow(row);
                } else {
                    JOptionPane.showMessageDialog(null, "La sección esta en uso por lo que no se puede eliminar", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

            @Override
            public void onView(int id) {
                //
            }
        };
        this.tablaSecciones.getColumnModel().getColumn(4).setCellRenderer(new TableActionCellRender());
        this.tablaSecciones.getColumnModel().getColumn(4).setCellEditor(new TableActionCellEditor(event));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        crearSeccionButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSecciones = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        volverButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1098, 700));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("LISTADO DE SECCIONES");

        crearSeccionButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        crearSeccionButton.setText("Crear sección");
        crearSeccionButton.setPreferredSize(new java.awt.Dimension(93, 23));
        crearSeccionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearSeccionButtonActionPerformed(evt);
            }
        });

        tablaSecciones.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        tablaSecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Cantidad", "Localidad", "Acciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaSecciones.setRowHeight(30);
        jScrollPane1.setViewportView(tablaSecciones);
        if (tablaSecciones.getColumnModel().getColumnCount() > 0) {
            tablaSecciones.getColumnModel().getColumn(0).setMinWidth(0);
            tablaSecciones.getColumnModel().getColumn(0).setPreferredWidth(0);
            tablaSecciones.getColumnModel().getColumn(0).setMaxWidth(0);
            tablaSecciones.getColumnModel().getColumn(1).setResizable(false);
            tablaSecciones.getColumnModel().getColumn(1).setPreferredWidth(75);
            tablaSecciones.getColumnModel().getColumn(2).setResizable(false);
            tablaSecciones.getColumnModel().getColumn(2).setPreferredWidth(16);
            tablaSecciones.getColumnModel().getColumn(3).setResizable(false);
            tablaSecciones.getColumnModel().getColumn(3).setPreferredWidth(86);
            tablaSecciones.getColumnModel().getColumn(4).setResizable(false);
            tablaSecciones.getColumnModel().getColumn(4).setPreferredWidth(12);
        }

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo-sm.png"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        volverButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        volverButton.setText("Volver");
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(282, 282, 282)
                .addComponent(jLabel1)
                .addContainerGap(373, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(volverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(crearSeccionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {crearSeccionButton, volverButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearSeccionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {crearSeccionButton, volverButton});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearSeccionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearSeccionButtonActionPerformed
        // TODO add your handling code here:
        CrearSeccion crearSeccion = new CrearSeccion(this);
        crearSeccion.setVisible(true);
    }//GEN-LAST:event_crearSeccionButtonActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        Home home = new Home();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel5MousePressed

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        Home home = new Home();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_volverButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarSecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarSecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarSecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarSecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarSecciones().setVisible(true);
            }
        });
    }

    private void cargarListaSecciones() {
        ArrayList<Seccion> listaDeSecciones = this.fb.getControladorSeccion().obtenerLasSecciones();
        ArrayList<Localidad> listaDeLocalidades = this.fb.getControladorLocalidad().obtenerLasLocalidades();
        DefaultTableModel modelo = (DefaultTableModel) this.tablaSecciones.getModel();
        for (Seccion sec : listaDeSecciones) {
            String localidad = "";
            for (Localidad loc : listaDeLocalidades) {
                if (sec.getIdLocalidad() == loc.getIdLocalidad()) {
                    localidad = loc.getNombre();
                }
            }
            Object[] row = {sec.getIdSeccion(), sec.getNombre(), sec.getCantidad(), localidad};
            modelo.addRow(row);
        }
        
        this.tablaSecciones.getColumnModel().getColumn(1).setCellRenderer(new CenterRenderer());
        this.tablaSecciones.getColumnModel().getColumn(2).setCellRenderer(new CenterRenderer());
        this.tablaSecciones.getColumnModel().getColumn(3).setCellRenderer(new CenterRenderer());
    }
    public void actualizarTabla(){
        DefaultTableModel model = (DefaultTableModel)  this.tablaSecciones.getModel();
        int i = this.tablaSecciones.getRowCount();
        while (i != 0) {
            model.removeRow(0);
            i--;
        }
        this.cargarListaSecciones();
        this.tablaSecciones.getColumnModel().getColumn(4).setCellRenderer(new TableActionCellRender());
        this.tablaSecciones.getColumnModel().getColumn(4).setCellEditor(new TableActionCellEditor(event));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearSeccionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSecciones;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
